Fix zero byte blob puts
regclient/regclient pull request #610
Opened 2023-11-22 11:12 UTC by edigaryev

It makes no sense to perform a chunked upload of zero-byte blobs.

@sudo-bmitch I also don't understand why should `BlobPut()` mess with the descriptor's size when it's zero, perhaps you could clarify this.

2023-11-22 16:13 UTC, sudo-bmitch requested changes
A size==0 can be an attempt to push an empty blob, which is not supported on all registries. Or it can be an attempt to push a blob without knowing the size/digest of the content being pushed in advance (e.g. a streaming source that builds the tar + compresses on the fly without caching in memory). This breaks support for the latter scenario.

2023-11-22 16:30 UTC, edigaryev commented
> A size==0 can be an attempt to push an empty blob, which is not supported on all registries.

But the regclient currently will still push it, however, in a way more complicated way.

>Or it can be an attempt to push a blob without knowing the size/digest of the content being pushed in advance (e.g. a streaming source that builds the tar + compresses on the fly without caching in memory).

That makes sense.

I've extracted and force-pushed the remaining changes (https://github.com/regclient/regclient/pull/610/commits/7c6eafae51fea8d335749628375b14c6f201016f and https://github.com/regclient/regclient/pull/610/commits/b0c5221a332a6e4fcfba950a0fcccb9db19d127b) to improve the code for the future reader, PTAL.

2023-11-22 19:54 UTC, sudo-bmitch commented
> > A size==0 can be an attempt to push an empty blob, which is not supported on all registries.
> 
> But the regclient currently will still push it, however, in a way more complicated way.

There's other options for comparing that zero value that can be considered. Are there errors you're encountering? Tests that could show why the current behavior is wrong?

2024-01-03 21:01 UTC, sudo-bmitch commented
This was fixed in #637 with a different take on how the zero length blob is handled.

2024-01-03 21:01 UTC, closed without merging